import Banner from "@/components/Banner";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Products from "@/components/Products";
import TopFooter from "@/components/TopFooter";
import { Product } from "@/type";
import Head from "next/head";

interface Props {
  productData : Product
}

export default function Home({productData}:Props) {

  return (
    <>
      <Head>
        <title>Shop-Next</title>
        <meta name="description" content="Generated by Create Next App" />
        <meta name="viewport" content="width=device-width , initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-lightBlue">
        <div className="max-w-contentContainer mx-auto bg-white">
          <Banner />
          <Products productData={productData} />
        </div>
      </main>
    </>
  );
}

//========================= SSR Data Fetching starts Here
export const getServerSideProps = async() => {
  const productData = await(
    await fetch("http://localhost:3000/api/productdata")
  ).json();

  return {
    props : {productData}
  }
  
}